import type { JobPostingItem } from "./types";

export const defaultJobs: JobPostingItem[] = [
  {
    "id": "curated-langchain-intern",
    "company": "LangChain",
    "title": "Generative AI & LLM Systems Engineering Intern",
    "location": "Remote (Worldwide)",
    "url": "https://boards.greenhouse.io/langchain/jobs/4320145007",
    "description": "Build state-of-the-art agentic workflows, LangGraph multi-agent execution engines, and evaluations for production LLM applications. Working directly with LangChain and LangGraph core engineers.",
    "postedDate": "Recently",
    "source": "Greenhouse",
    "techStack": [
      "LangChain",
      "LangGraph",
      "Multi-Agent Workflows",
      "Autonomous Tool Calling",
      "FastAPI (REST & SSE)",
      "Python"
    ],
    "matchScore": 98,
    "matchReason": "🎓 Fresher / Intern Friendly — Direct fit: LangGraph, LangChain, Multi-Agent Workflows, and Autonomous Tool Calling.",
    "isInternship": true,
    "companyStage": "Series A (Agent Framework)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-composio-applied-ai",
    "company": "Composio",
    "title": "Member Technical Staff - Applied AI Engineer",
    "location": "Bangalore, India",
    "url": "https://jobs.ashbyhq.com/composio/a2fd44d1-1457-4248-8d9c-905953016398",
    "description": "Build autonomous tool-calling integrations, multi-agent execution pipelines, and agent reliability guardrails for 200+ developer tools. Working with LangChain, LangGraph, and Python.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Autonomous Tool Calling",
      "Multi-Agent Workflows",
      "LangGraph",
      "LangChain",
      "FastAPI (REST & SSE)",
      "Python"
    ],
    "matchScore": 98,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — Direct founder review. Core alignment with your Tool Calling, LangGraph & Multi-Agent stack.",
    "isInternship": false,
    "companyStage": "Seed (Agent Tooling & Workflows)",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-sarvam-agent-eng",
    "company": "Sarvam AI",
    "title": "Agent Engineer (Early Career / Intern)",
    "location": "Bengaluru, India",
    "url": "https://jobs.ashbyhq.com/sarvam/f3376204-1c2d-42a8-bf4a-1a0eec2fbc3c",
    "description": "Design and deploy frontier GenAI agents, contextual retrieval systems (RAG), and evaluation pipelines using Python, FastAPI, and PyTorch for India's premier sovereign AI lab.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Multi-Agent Workflows",
      "RAG & Vector Search",
      "FastAPI (REST & SSE)",
      "PyTorch",
      "Python"
    ],
    "matchScore": 97,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — Seed team (India GenAI Lab). Strong fit for your Agent, RAG & FastAPI background.",
    "isInternship": true,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-mem0-ai-eng",
    "company": "Mem0",
    "title": "Full Stack AI Engineer (Agent Memory & Vector Search)",
    "location": "Remote (Worldwide)",
    "url": "https://jobs.ashbyhq.com/mem0/642f00ec-c220-48a5-9a4d-4af67875032c",
    "description": "Develop long-term memory for AI agents, multi-agent context engineering, and pgvector/Supabase retrieval systems. Working with Python, Next.js, and FastAPI.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Multi-Agent Workflows",
      "Vector DB",
      "pgvector & Supabase",
      "FastAPI (REST & SSE)",
      "Next.js & React",
      "Python"
    ],
    "matchScore": 96,
    "matchReason": "🚀 Direct founder review (Seed). Matches your stack in Context Engineering, pgvector, Vector DB & FastAPI.",
    "isInternship": false,
    "companyStage": "Seed (Agent Memory)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-scaleai-fde-india",
    "company": "Scale AI",
    "title": "Forward Deployed Engineer, Gen AI",
    "location": "Bengaluru, India",
    "url": "https://boards.greenhouse.io/scaleai/jobs/4523992005",
    "description": "Deploy enterprise generative AI solutions, RAG pipelines, and model evaluation guardrails for mission-critical client applications. Working with Python, FastAPI, and LangChain.",
    "postedDate": "Recently",
    "source": "Greenhouse",
    "techStack": [
      "RAG & Vector Search",
      "Pydantic Guardrails",
      "LangChain",
      "FastAPI (REST & SSE)",
      "AWS & Docker (CI/CD)",
      "Python"
    ],
    "matchScore": 96,
    "matchReason": "🇮🇳 India Role — High callback GenAI team. Strong fit for your RAG, Guardrails, and FastAPI stack.",
    "isInternship": false,
    "companyStage": "Growth (AI Data & Evals)",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-llamaindex-rag-eng",
    "company": "LlamaIndex",
    "title": "Developer Engineer - RAG & Agent Frameworks",
    "location": "Remote (Global)",
    "url": "https://jobs.ashbyhq.com/llamaindex",
    "description": "Build advanced Corrective RAG (CRAG) pipelines, evaluation harnesses (DeepEval/Ragas), and multi-agent retrieval tools for developers. Python, TypeScript, and Vector DBs.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Corrective RAG (CRAG)",
      "RAG & Vector Search",
      "Ragas & DeepEval",
      "Vector DB",
      "Python",
      "TypeScript"
    ],
    "matchScore": 96,
    "matchReason": "⚡ High Callback: Series A team (LLM Data). Core alignment with your Corrective RAG (CRAG) & Vector DB stack.",
    "isInternship": false,
    "companyStage": "Series A (LLM Data)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "google-epifitechnologi-1790189993-0",
    "company": "Epifi Technologies",
    "title": "GenAI Product Builder Intern",
    "location": "Bengaluru, Karnataka, India",
    "url": "https://jobs.lever.co/epifi/4f5b7548-ea0a-4be0-816b-11d712853169",
    "description": "Test duplicate insertion",
    "postedDate": "Recently",
    "source": "Google (via Lever)",
    "techStack": [],
    "matchScore": 92,
    "matchReason": "Matching role.",
    "isInternship": true,
    "companyStage": "Seed / Series A",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-d2d593e6-be5a-4431-b1fa-86f18d1c7edf",
    "company": "Sarvam",
    "title": "DevOps Engineer",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/d2d593e6-be5a-4431-b1fa-86f18d1c7edf",
    "description": "About the Role\n\nSarvam’s Work Agents team builds the harness for developing, evaluating, and serving autonomous agents at scale. The harness is the backbone behind how agents are run, tested, orchestrated, and deployed and it needs infrastructure that is as reliable and fast-moving as the agents themselves.\n\nThis role sits across both sides of infrastructure. You will build the tooling, pipelines, and automation that make the harness self-service and reproducible, and you will operate the day-to-day keeping CI/CD healthy, environments consistent, networks and tunnels up, and deployments running smoothly. It is a mix of engineering and operations, not pure SRE-on-call and not pure platform-product work.\n\nYou should be a hands-on DevOps engineer fluent in Kubernetes, comfortable with cloud infrastructure (AWS primarily, Azure secondarily), and literate in the networking and CI/CD concerns that keep a multi-cluster, multi-tenant environment running. You will work closely with the engineer",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Multi-Agent Workflows",
      "AWS & Docker (CI/CD)"
    ],
    "matchScore": 91,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Autonomous Tool Calling, AWS.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-composio-cceb9883-7967-45a9-8e37-ed72cec3deff",
    "company": "Composio",
    "title": "Product  Ops Intern",
    "location": "Bangalore",
    "url": "https://jobs.ashbyhq.com/composio/cceb9883-7967-45a9-8e37-ed72cec3deff",
    "description": "WHO ARE WE?\n\nAt Composio, we are building infrastructure that allows agents to communicate with the tools you use for work including Github, Gmail, Notion, Salesforce, etc. We are a small team of engineers wrangling problems from context to search, that help us provide the most capable bridge between your agents and your tools.\n\nWe raised a $25M Series A from Lightspeed https://lsvp.com/stories/investing-in-composio-building-the-backbone-of-ai-agent-intelligence/ with some incredible angels like Guillermo Rauch (CEO of Vercel), Dharmesh Shah (CTO of Hubspot), Gokul Rajaram. Beginning of this year we 3x our ARR, our customer range from your friends in the YC batch to Wabi, Glean, Zoom and many more.\n\n\n\nWHAT WILL YOU DO?\n\nBuilding Agents\n\n - Write down the manual playbook as you run it, then work out what a person should never have to touch again\n\n - Build AI agents that watch inboxes, send the follow-ups, and keep the tracker current on their own\n\n - Turn repetitive outreach and trackin",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 91,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — Direct founder review (Seed (Agent Tooling & Workflows)). Matches your stack in Autonomous Tool Calling.",
    "isInternship": true,
    "companyStage": "Seed (Agent Tooling & Workflows)",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-f462051e-ec76-45cf-96c5-e0192dd4dcc6",
    "company": "Sarvam",
    "title": "Product Manager On-Device & Edge AI",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/f462051e-ec76-45cf-96c5-e0192dd4dcc6",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India's full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India's leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n\n\nAbout the Role\n\nSarvam is our on-device AI product line — purpose-built for enterprise deployments where data sovereignty, low latency, and offline reliability are non-negotiable. We're looking for a Product Manager who understands enterprise AI deeply: the IT admin personas, the procurement cycles, the compliance requirements, and the day-to-day friction that determines whether an AI tool gets embedded into workflows or quietly abandoned.\n\nYou'll own the product roadmap for drive B2B GTM alignment, and ",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 91,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Multi-Agent Workflows, Autonomous Tool Calling.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-cognition-e6f55fdf-151d-4282-a600-b92e4124732f",
    "company": "Cognition",
    "title": "QA Engineer - APAC",
    "location": "India",
    "url": "https://jobs.ashbyhq.com/cognition/e6f55fdf-151d-4282-a600-b92e4124732f",
    "description": "WE ARE AN APPLIED AI LAB BUILDING END-TO-END SOFTWARE AGENTS.\n\nWe're the makers of Devin, the first AI software engineer. \n\nOur team is extremely talent-dense. Among our founding team, we have world-class competitive programmers, former founders, and leaders from companies at the cutting edge of AI including Scale AI, Palantir, Cursor, Waymo, Tesla, Lunchclub, Modal, Google DeepMind, and Nuro.\n\nBuilding Devin is just the first step—our hardest challenges still lie ahead. If you’re excited to solve some of the world’s biggest problems and build AI that can reason on real-world tasks, apply to join us.\n\n\nABOUT THE ROLE\n\n\n\n\n\n\nKEY RESPONSIBILITIES\n\n - Own end-to-end product quality across AI workflows: Test Windsurf and Devin across onboarding flows, chat interactions, multi-file edits, agentic task execution, and autonomous workflows—thinking like a developer and testing like a user.\n\n - Design and execute comprehensive test strategies: Build and run functional, regression, integration, e",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Multi-Agent Workflows"
    ],
    "matchScore": 90,
    "matchReason": "🇮🇳 India Role — Early AI team (Series A (Devin Autonomous AI)). Matches your stack in Multi-Agent Workflows, Autonomous Tool Calling.",
    "isInternship": false,
    "companyStage": "Series A (Devin Autonomous AI)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "google-datavivtechnolo-1790189773-5",
    "company": "Dataviv Technologies",
    "title": "Gen Immersive AI tool Intern",
    "location": "India",
    "url": "https://www.glassdoor.co.in/job-listing/gen-immersive-ai-tool-intern-dataviv-technologies-JV_KO0,28_KE29,49.htm?jl=1010218993957",
    "description": "This internship focuses on immersive AI tool development in India. The role offers an estimated salary of ₹4L - ₹7L.",
    "postedDate": "Recently",
    "source": "Google (via Glassdoor)",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 89,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Autonomous Tool Calling.",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "google-swarmlens-1790189773-4",
    "company": "SwarmLens",
    "title": "Artificial Intelligence Intern",
    "location": "India",
    "url": "https://in.linkedin.com/jobs/view/artificial-intelligence-intern-at-swarmlens-4320820005",
    "description": "This internship supports the development, implementation, and evaluation of Generative AI models, AI agents, and RAG systems. Compensation is ₹7-10K during the internship period.",
    "postedDate": "Recently",
    "source": "Google (via LinkedIn)",
    "techStack": [
      "RAG & Vector Search",
      "LLM Engineering"
    ],
    "matchScore": 89,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Corrective RAG (CRAG).",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "google-universalprinte-1790189569-0",
    "company": "Universal Printers",
    "title": "Generative Ai Intern",
    "location": "Pune, India",
    "url": "https://in.indeed.com/rc/clk?jk=dba9462a010b3e8f&bb=OvYgPrU8Tl4RiP-0qU6UcfSMdsLUdemrKC6ujUku7p-tMEEEEimLZAqINE2ls2JmIlyKUyB67DZrqdpZbTMEloBes5pU7Ck0kJbBQKxS5fhMCiWk1mC0TYHIS4zl22pCbb7lJWyUF1bAEa9yZNly862mc4h2QxNx&xkcb=SoCq67M2fl6bNBSTzB0LbzkdCdPP&fccid=678ec8d65fef33e6&cmp=Universal-Printers&ti=Generative+Ai+Intern&vjs=3",
    "description": "The intern will work with large language models (LLMs), prompt engineering, AI agents, and machine learning tools. The role involves creating innovative solutions for real-world problems.",
    "postedDate": "Recently",
    "source": "Google (via Indeed)",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 89,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Autonomous Tool Calling.",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "ashby-signoz-f4273207-6f44-40cc-81b0-b1d8b288dc45",
    "company": "Signoz",
    "title": "AI GTM Engineer",
    "location": "India",
    "url": "https://jobs.ashbyhq.com/signoz/f4273207-6f44-40cc-81b0-b1d8b288dc45",
    "description": "AI GTM ENGINEER\n\n\n\n\nABOUT THE ROLE\n\nWe’re looking for an AI GTM Engineer  to own the systems, data, and processes behind our marketing engine.\n\nThis is a hands-on role. You’ll work across Marketing, Sales, Product and Growth to make sure our campaigns run smoothly, our data is reliable, and we’re continuously improving conversion across the funnel.\n\nYou should be equally comfortable building a dashboard, fixing an email workflow, creating an account list, and figuring out why a conversion rate dropped.\n\nWhat you'll build\n\n - Signal queues for sales. Define and ship signals such as ICP signups, usage spikes, expansion and win-back triggers, delivered to reps as ranked queues in HubSpot and Slack.\n\n - Customer health and alerting. Build usage and billing-spike alerts so CS and Sales act on changes in paying accounts.\n\n - A trusted funnel. Build one source of truth for signup to SQL to closed-won in BigQuery, trusted by every GTM lead.\n\n - AI-native GTM workflows. Use LLMs and agents for ",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 88,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (YC W21 Open Source)). Matches your stack in Multi-Agent Workflows.",
    "isInternship": false,
    "companyStage": "Seed (YC W21 Open Source)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-86ae80f8-b7eb-43a4-afde-fef58e77e23e",
    "company": "Sarvam",
    "title": "Backend Engineer, Chanakya",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/86ae80f8-b7eb-43a4-afde-fef58e77e23e",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India's full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India's leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n \n\nAbout the Role\n\nBackend Engineers on this team are builders, not maintainers. You will design and implement the core system infrastructure that powers Sarvam's 'atoms': MCP servers, on-prem deployment tooling, document ingestion pipelines, agentic backends, and API layers. These systems run in classified, air-gapped, and operationally constrained environments — or in enterprise environments with their own security, compliance, and integration constraints.\n\nThe architecture decisions you make will be inh",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Multi-Agent Workflows"
    ],
    "matchScore": 88,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Autonomous Tool Calling.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "google-enverus-1790189993-1",
    "company": "Enverus",
    "title": "Technical Product Intern GenAI",
    "location": "Bangalore, India",
    "url": "https://www.shine.com/jobs/technical-product-intern-genai/enverus/19342761",
    "description": "This is a 6-month internship requiring work from the Bangalore office. Key responsibilities include analyzing product usage, AI performance, and customer feedback to drive product improvements.",
    "postedDate": "Recently",
    "source": "Google (via Shine)",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 86,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Python & AI Engineering.",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "google-atomicads-1790189773-1",
    "company": "AtomicAds",
    "title": "Artificial Intelligence Intern",
    "location": "India",
    "url": "https://in.linkedin.com/jobs/view/artificial-intelligence-intern-at-atomicads-4296064434",
    "description": "Seeking a driven Gen AI Developer Intern passionate about building the next wave of generative AI-powered applications. The role focuses on developing innovative AI solutions.",
    "postedDate": "Recently",
    "source": "Google (via LinkedIn)",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 86,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Python & AI Engineering.",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "google-thegenacademy-1790189773-0",
    "company": "The Gen Academy",
    "title": "AI Intern",
    "location": "India",
    "url": "https://in.linkedin.com/jobs/view/ai-intern-at-the-gen-academy-4376413348",
    "description": "This role seeks a hands-on Data Science intern to build scrappy prototypes and design AI coursework. Responsibilities include learning fast and teaching others within the AI domain.",
    "postedDate": "Recently",
    "source": "Google (via LinkedIn)",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 86,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Python & AI Engineering.",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "google-enverus-1790189773-3",
    "company": "Enverus",
    "title": "Product Intern - Machine Learning & Gen-AI",
    "location": "India",
    "url": "https://www.shine.com/jobs/product-intern-machine-learning-gen-ai-india/enverus/19387494",
    "description": "A 6-month internship focused on deepening technical skills through impactful, production-focused AI initiatives. The role involves Machine Learning and Gen-AI.",
    "postedDate": "Recently",
    "source": "Google (via Shine)",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 86,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Python & AI Engineering.",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "google-avgcstudios-1790189773-6",
    "company": "AVGC Studios",
    "title": "Gen AI Artist Intern",
    "location": "India",
    "url": "https://www.glassdoor.co.in/job-listing/gen-ai-artist-intern-avgc-studios-JV_IC4477468_KO0,20_KE21,33.htm?jl=1010241693241",
    "description": "This internship is for a Gen AI Artist, likely involving creative applications of generative AI. The role is based in India.",
    "postedDate": "Recently",
    "source": "Google (via Glassdoor)",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 86,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Python & AI Engineering.",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "google-linkedinindia-1790189773-7",
    "company": "LinkedIn India",
    "title": "Generative AI Intern",
    "location": "Bengaluru, India",
    "url": "https://myinternships.in/internships/linkedin-india-is-hiring-generative-ai-intern-bengaluru-14sew",
    "description": "LinkedIn India is hiring a Generative AI Intern in Bengaluru for a 12-month, work-from-office role. The position offers a ₹15000/month stipend.",
    "postedDate": "Recently",
    "source": "Google (via MyInternships.in)",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 86,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Python & AI Engineering.",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "google-skillvedanth-1790189773-8",
    "company": "SKILL VEDANTH",
    "title": "Gen AI INTERN",
    "location": "India",
    "url": "https://in.linkedin.com/jobs/view/gen-ai-intern-at-skill-vedanth-4387958968",
    "description": "This internship involves researching AI advancements, building and implementing AI models and algorithms, and testing generative processes. Documentation of findings is also a key responsibility.",
    "postedDate": "Recently",
    "source": "Google (via LinkedIn)",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 86,
    "matchReason": "🇮🇳 India Role | 🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Python & AI Engineering.",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "gh-inmobi-8073988",
    "company": "Inmobi",
    "title": "SDE II - AI",
    "location": "Bangalore",
    "url": "https://job-boards.greenhouse.io/inmobi/jobs/8073988",
    "description": "&lt;div class=&quot;content-intro&quot;&gt;&lt;p&gt;&lt;strong&gt;InMobi (Corporate)&lt;/strong&gt;&lt;/p&gt;\n&lt;p&gt;InMobi Group is a global technology company shaping the future of agentic commerce and advertising. Through its ecosystem of businesses — including InMobi Advertising and flagship consumer platform Glance — InMobi leverages data, machine learning, and generative AI to help brands reach audiences more precisely and consumers discover products more intuitively. Glance, which is pioneering new models of agentic commerce, is owned and operated by Glance InMobi Pte. Ltd., a non-consolidated subsidiary of InMobi Pte. Ltd.&lt;/p&gt;\n&lt;p&gt;&lt;strong&gt;InMobi Advertising&lt;/strong&gt;&lt;/p&gt;\n&lt;p&gt;InMobi Advertising, part of global technology company InMobi, is an agentic advertising platform helping brands and merchants achieve their business outcomes. Through its proprietary intelligence, AI-led solutions, and vast consumer reach — including flagship consumer plat",
    "postedDate": "Recently",
    "source": "Greenhouse",
    "techStack": [
      "Multi-Agent Workflows",
      "LLM Engineering"
    ],
    "matchScore": 86,
    "matchReason": "🇮🇳 India Role — GenAI team (AI & AdTech). Matches your stack in Corrective RAG (CRAG).",
    "isInternship": false,
    "companyStage": "AI & AdTech",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "gh-scaleai-4549048005",
    "company": "Scaleai",
    "title": "Forward Deployed Engineer, Gen AI",
    "location": "India",
    "url": "https://job-boards.greenhouse.io/scaleai/jobs/4549048005",
    "description": "&lt;p&gt;&lt;strong&gt;About Scale AI&lt;/strong&gt;&lt;/p&gt;\n&lt;p&gt;At Scale AI, our mission is to accelerate the development of AI applications. For 10 years, Scale has been the leading AI data foundry, helping fuel the most exciting advancements in AI, including generative AI, defense applications, and autonomous vehicles. With our recent Series F round, we’re accelerating the abundance of frontier data to pave the road to Artificial General Intelligence (AGI) and building upon our prior model evaluation work with enterprise customers and governments to deepen our capabilities and offerings for public and private evaluations.&lt;/p&gt;\n&lt;p&gt;&lt;strong&gt;About Data Engine&lt;/strong&gt;&lt;/p&gt;\n&lt;p&gt;Our Generative AI Data Engine powers the world’s most advanced LLMs and generative models through world-class RLHF (Reinforcement Learning with Human Feedback), human data generation, model evaluation, safety, and alignment. The data we produce is some of the most critical w",
    "postedDate": "Recently",
    "source": "Greenhouse",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 86,
    "matchReason": "🇮🇳 India Role — GenAI team (Growth (AI Data)). Matches your stack in Autonomous Tool Calling.",
    "isInternship": false,
    "companyStage": "Growth (AI Data)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-cartesia-6d860f5a-b9d9-4df2-b5e5-b12ac80632a4",
    "company": "Cartesia",
    "title": "Forward Deployed Engineer (India)",
    "location": "Bangalore",
    "url": "https://jobs.ashbyhq.com/cartesia/6d860f5a-b9d9-4df2-b5e5-b12ac80632a4",
    "description": "ABOUT CARTESIA\n\nOur mission is to architect AI that learns from and interacts with the world like humans do.\n\nWe're pioneering the model architectures that will make this possible. Our founding team met as PhDs at the Stanford AI Lab, where we invented State Space Models or SSMs, a new primitive for training efficient, large-scale foundation models. Our team combines deep expertise in model innovation and systems engineering paired with a design-minded product engineering team to build and ship cutting edge models and experiences.\n\nWe're funded by leading investors at Index Ventures and Lightspeed Venture Partners, along with Factory, Conviction, A Star, General Catalyst, SV Angel, Databricks and others. We're fortunate to have the support of many amazing advisors, and 90+ angels across many industries, including the world's foremost experts in AI.\n\n\n\n\nABOUT THE ROLE\n\nWe’re hiring a Forward Deployed Engineer to advance our mission of building real-time multimodal intelligence by embedd",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (Voice AI)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (Voice AI)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-255816b4-c44d-481c-a093-73ae114d1952",
    "company": "Sarvam",
    "title": "Researcher, Vision",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/255816b4-c44d-481c-a093-73ae114d1952",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India's full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India's leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n \n\nAbout the Role\n\nYou will work across the full lifecycle of vision-language model (VLM) development — data, training, evaluation, and production. The team's scope will evolve as the field does; we want researchers who are comfortable with that and can lead.\n\n \n\nWhat You'll Do\n\n• Research vision-language architectures — encoders, fusion mechanisms, pretraining objectives, and scaling behaviour\n\n• Design training methods (pretraining, SFT, RLHF, DPO) adapted for multilingual VLMs\n\n• Investigate data strate",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-87d5a5af-ea7d-4b94-a0fa-81dc64e54907",
    "company": "Sarvam",
    "title": "Strategic Deployment Engineer, Chanakya",
    "location": "Delhi",
    "url": "https://jobs.ashbyhq.com/sarvam/87d5a5af-ea7d-4b94-a0fa-81dc64e54907",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India's full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India's leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n \n\nAbout the Role\n\nStrategic Deployment Engineers are Sarvam's forward-deployed technical assets. Embedded with clients, you own the full lifecycle of AI system deployments — including in air-gapped, classified, and on-prem environments — and in complex enterprise accounts where standard playbooks don't apply. You are the technical SPOC for your assigned accounts. Success is measured by whether the system works, the client trusts us, and the deployment creates durable capability — not by ticket closure. Yo",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-e7f783e8-6378-4158-97d5-48a397a91698",
    "company": "Sarvam",
    "title": "ML Ops Engineer, Chanakya",
    "location": "Delhi",
    "url": "https://jobs.ashbyhq.com/sarvam/e7f783e8-6378-4158-97d5-48a397a91698",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India's full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India's leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n \n\nAbout the Role\n\nThe MLOps Engineer owns the model lifecycle across all defence and strategic sector deployments — from serving infrastructure and monitoring to evaluation pipelines and environment management. You ensure the system is always on, always accurate, and always auditable.\n\nYou will work across both layers: supporting Strategic Deployment Engineers in the field, and owning the model deployment infrastructure for new products being built by the product engineering team. The standards here are u",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-10a352d0-a65b-4599-8998-e09deef34349",
    "company": "Sarvam",
    "title": "Frontend Engineer, Chanakya",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/10a352d0-a65b-4599-8998-e09deef34349",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India's full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India's leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n \n\nAbout the Role\n\nThese are not form-and-table frontend roles. The frontend engineers on this team build the interfaces that sit on top of Sarvam's AI stack in some of the most demanding environments in the country. You will own the frontend layer of multiple 'atoms' — replicable, deployable product components — and work closely with backend engineers, the PM, and the deployment team. These interfaces must work in offline-first, low-bandwidth, hardened client environments, not just on a MacBook over broad",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-af865840-f90e-4e16-bf15-8a3a9c0b434c",
    "company": "Sarvam",
    "title": "GTM Manager On-Device AI",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/af865840-f90e-4e16-bf15-8a3a9c0b434c",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India's full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India's leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n\n\nAbout the Role\n\nSarvam On-Device AI is built for enterprise and OEM deployments where data sovereignty, edge performance, and deep workflow integration are the differentiators. We're looking for a GTM Manager to own the go-to-market motion for On-Device AI as an individual contributor — from growth strategy and demand generation to partner ecosystem development and sales enablement.\n\nThis is a hands-on, quota-aware role. You'll work directly with enterprise accounts, OEM and PC hardware partners, and int",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-2dcb062d-e42b-408d-be15-59ddde900984",
    "company": "Sarvam",
    "title": "ML Researcher, Foundational Models",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/2dcb062d-e42b-408d-be15-59ddde900984",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India’s full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India’s leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n\n\nAbout the Role\n\nYou'll work on the open-ended questions that decide what our next models look like. This is not a fine-tuning role. It's not an \"apply known recipes\" role. We're looking for a researcher who can take a vague hunch about architecture, optimization, data composition, or training dynamics, design the right ablations, run them at meaningful scale, and turn the result into a decision that ships in a production training run.\n\nYou will have direct access to large compute and a tight feedback loo",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-2d72a541-c805-4bd9-81cd-ac2db98611fa",
    "company": "Sarvam",
    "title": "ML Engineer (Data), Foundational Models",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/2d72a541-c805-4bd9-81cd-ac2db98611fa",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India’s full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India’s leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n\n\nAbout the Role\n\nYou will own the data infrastructure that feeds our next family of foundational models. This means building petabyte-scale curation and filtering pipelines, designing the systems that decide what goes into a training run and in what proportion, and treating data quality with the same rigor a research team would treat an architectural choice.\n\nThis is not a glue-code role. The data work at a serious pretraining lab is engineering- and research-heavy: deduplication at scale, quality models,",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-b07dfd8a-208d-43c1-a811-f1c447df26f9",
    "company": "Sarvam",
    "title": "Backend Engineer - Studio Media Platform",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/b07dfd8a-208d-43c1-a811-f1c447df26f9",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India’s full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India’s leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\nAbout the Role\n\nWe are hiring a Backend Engineer to work across Sarvam’s Studio media platform — spanning AI dubbing, live translation, and the shared service foundation that powers all Studio products (voice cloning, stem separation, lip sync, music generation, and more). You will build and maintain production services, ML pipeline libraries, and platform SDKs that together enable multilingual media processing at scale for enterprise customers and Sarvam Studio users.\n\nThe work cuts across multiple codeba",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-6ad226cd-9400-41b6-9c64-db35b7d24516",
    "company": "Sarvam",
    "title": "Performance Engineer, On-Device Inference",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/6ad226cd-9400-41b6-9c64-db35b7d24516",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India’s full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India’s leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\nAbout the Role\n\nTake Sarvam models from research-handoff state to production-ready artifacts on at least two of our target chipsets (Intel xPU, ARM xPU, Apple xPU, Nvidia / AMD GPUs). You'll own 1 - 2 (model, chipset) pairs end-to-end and partner with the consuming app team during integration.\n\nWhat You’ll Do\n\n - Quantize, validate accuracy, benchmark, and document. Author the deployment workbook for each pair you own.\n\n - Embed part-time with consuming teams during integration; debug perf and accuracy iss",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-fcb15601-6440-41f7-aa79-b9992057a4b2",
    "company": "Sarvam",
    "title": "Platform Engineer - AI Infrastructure",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/fcb15601-6440-41f7-aa79-b9992057a4b2",
    "description": "Platform Engineer - AI Infrastructure\n\nAbout Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India’s full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India’s leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\nAbout the Role\n\nSarvam runs a large, multi-vendor GPU fleet that serves two demanding workloads on the same physical infrastructure: training jobs that span hundreds of GPUs, and inference services that must hold a flat p99 under production load. This role builds the platform that sits on top of that fleet - the scheduling, scaling, multi-tenancy, serving, and self-service layers that let our ML teams use thousands of GPUs without a human in the loop for every job.\n\nT",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-de7eba10-6fff-4fa3-8d70-526f2cf58eb7",
    "company": "Sarvam",
    "title": "Frontend Engineer, Vision ",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/de7eba10-6fff-4fa3-8d70-526f2cf58eb7",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India's full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India's leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\nAbout the Team\n\nSarvam's research teams build our own vision-language models for OCR and structured extraction. This team builds everything around them — the serving harness that turns a 3B or 30B in-house model into a production document intelligence platform.\n\nThe bet is specific: with the right harness — routing, decomposition, retries, verification, ensembling, layout awareness, confidence calibration — a small sovereign model should match or beat what teams today get from frontier hosted models like G",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-50cc51f1-0229-460a-b60b-bf747059f034",
    "company": "Sarvam",
    "title": "Developer Relations Engineer  - Community Manager",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/50cc51f1-0229-460a-b60b-bf747059f034",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India’s full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India’s leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n \n\nAbout the Role\n\nDevRel at Sarvam is part engineering, part content, part community — and this role manages the community pillar.\n\nYou will be the person who makes Sarvam's developer community a place builders want to belong to. That means running our Discord day to day, designing and operating community programs — hackathons, meetups, office hours, workshops — and making sure every developer who shows up gets a great experience, whether they're asking their first question or shipping their tenth project",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-730c1766-ad62-4d5d-aa75-b5b0e03409aa",
    "company": "Sarvam",
    "title": "Developer Relations Engineer - Developer Advocate",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/730c1766-ad62-4d5d-aa75-b5b0e03409aa",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India’s full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India’s leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n \n\nAbout the Role\n\nDevRel at Sarvam is part engineering, part content, part community — and this role manages the code and content pillars.\n\n \n\nAs a Developer Advocate, you are a developer first. You build the demos, cookbooks, integrations, and technical content that show developers what's possible with Sarvam's models — and make it easy for them to ship. Your code and your writing are often the first experience a developer has with Sarvam, and you hold both to a high bar.\n\n \n\nAt the core of this role is ",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-72783205-b637-4431-9a0e-676a8223b063",
    "company": "Sarvam",
    "title": "Performance Engineer, Kernels",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/72783205-b637-4431-9a0e-676a8223b063",
    "description": "PERFORMANCE ENGINEER, KERNELS\n\nPart of Sarvam's Performance Engineering team. We are hiring two specialized performance roles - Kernels (this posting) and Inference (companion posting). They are a vertical stack: the kernels team authors the µs-level GPU code, and the inference team integrates it into a running serving stack and owns the system-level numbers. If your depth genuinely spans both, apply to either and tell us - but most candidates are strongest in one, and we hire for that depth.\n\n\n\nLocation: [Bengaluru / Chennai / Hybrid / On-site]  ·  Team: Performance Engineering  ·  Level: Senior\n\n\n\n\nABOUT THE TEAM\n\nSarvam serves multiple model families - small and large LLMs, Mixture-of-Experts, streaming Indic ASR, and multimodal - across a multi-node, multi-tenant fleet on H100 / H200 / B200. The Performance Engineering team owns the numbers the rest of the company plans against: how fast we serve, how much it costs, and how much we get out of every GPU. This team works at the inter",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-7d2faba2-21a1-4a8a-aff5-f708a6959195",
    "company": "Sarvam",
    "title": "Performance Engineer, Inference",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/7d2faba2-21a1-4a8a-aff5-f708a6959195",
    "description": "PERFORMANCE ENGINEER, INFERENCE\n\nPart of Sarvam's Performance Engineering team. We are hiring two specialized performance roles - Inference (this posting) and Kernels (companion posting). They are a vertical stack: the kernels team authors the µs-level GPU code, and the inference team integrates it into a running serving stack and owns the system-level numbers. If your depth genuinely spans both, apply to either and tell us - but most candidates are strongest in one, and we hire for that depth.\n\n\n\nLocation: [Bengaluru / Chennai / Hybrid / On-site]  ·  Team: Performance Engineering  ·  Level: Senior\n\n\n\n\nABOUT THE TEAM\n\nSarvam serves multiple model families - small and large LLMs, Mixture-of-Experts, Indic ASR & TTS, streaming models and multimodal models - across a multi-node, multi-tenant fleet of Hoppers and Blackwells. The Performance Engineering team owns the numbers the rest of the company plans against: how fast we serve, how much it costs, and how much we get out of every GPU. Th",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-36f89b00-2010-4d23-aae3-17a2f53d9eaa",
    "company": "Sarvam",
    "title": "Agent Engineer",
    "location": "Bengaluru",
    "url": "https://jobs.ashbyhq.com/sarvam/36f89b00-2010-4d23-aae3-17a2f53d9eaa",
    "description": "The distance between an AI system that works and one that millions of people rely on every day is where the real engineering lives. Crossing it is what Agent Engineers at Sarvam do.\n\nThe agents you build go into live operation at India's largest banks, insurers, NBFCs and government departments, and at some of the country's fastest-growing companies, handling millions of real interactions, measured against outcomes the customer wants to drive.\n\nThe hard part is not the first version. It is everything after: mapping the full space of what an agent has to handle so the scenarios that matter are covered by design rather than discovered in production, engineering for the failure modes instead of the happy path, and building the evals and instrumentation that make quality measurable, so drift surfaces in the data rather than in a customer escalation.\n\nWe treat agents as code. Not prompts someone tweaks in a console, but engineered artifacts: versioned, reviewed, and held to a regression sui",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "yc-hn-46296926",
    "company": "Sei AI",
    "title": "Sei AI (YC W22) is hiring an LLM Engineer (India, in-office, Chennai, Gurgaon)",
    "location": "Chennai, India",
    "url": "https://www.ycombinator.com/companies/sei/jobs/TYbKqi0-llm-engineer-mid-senior",
    "description": "Sei AI (YC W22) is hiring an LLM Engineer (India, in-office, Chennai, Gurgaon)\n\nOfficial Y Combinator batch startup opportunity. Direct founder/CTO hiring with high response rate.",
    "postedDate": "Recently",
    "source": "Y Combinator",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed / YC Startup). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed / YC Startup",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "ashby-sarvam-b2201b5e-1e96-497a-962c-bca1768f75fd",
    "company": "Sarvam",
    "title": "Embedded Infrastructure Engineer, Chanakya",
    "location": "Delhi",
    "url": "https://jobs.ashbyhq.com/sarvam/b2201b5e-1e96-497a-962c-bca1768f75fd",
    "description": "About Sarvam\n\nSarvam is building the bedrock of Sovereign AI for India. The company is developing India's full-stack sovereign AI platform, building across research, models, infrastructure and applications with a singular focus on making AI genuinely work for India. Sarvam works with leading enterprises and public institutions and is backed by Lightspeed, Peak XV, and Khosla Ventures. Sarvam partners with India's leading brands, including Tata Capital, SBI Life, CRED, IDFC, and LIC.\n\n \n\nAbout the Role\n\nEmbedded Infrastructure Engineers design, build, and maintain the data infrastructure that underpins AI system deployments at client sites. You work alongside Embedded Data Scientists and Strategic Deployment Engineers to ensure that terabyte-scale datasets can be ingested, stored, queried, and served to AI reasoning engines reliably and performantly.\n\nThis means building and operating data platforms that handle terabyte-scale persistent data stores and sustained large daily ingestion vo",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 85,
    "matchReason": "🇮🇳 India Role — Direct founder review (Seed (India GenAI Lab)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-braintrust-2a6c4ee9-063f-45d4-83ba-faf64b1f1a60",
    "company": "Braintrust",
    "title": "Open Source Engineer - Go",
    "location": "Remote",
    "url": "https://jobs.ashbyhq.com/braintrust/2a6c4ee9-063f-45d4-83ba-faf64b1f1a60",
    "description": "ABOUT THE COMPANY\n\nBraintrust is the agent observability platform. By actively applying intelligence to agent traces and automatically surfacing the most critical patterns, Braintrust gives teams the visibility to understand how agents behave in production and the tools to improve them.\n\nTeams at Notion, Stripe, Box, OpenAI, and Cloudflare use Braintrust to trace their agents, find the issues in their observability data, and run evals that tell them how to improve.\n\n\nABOUT THE ROLE\n\nWe’re hiring engineers to build the open-source libraries that customers use to observe, understand, and optimize how AI operates inside their production applications. These SDKs are a critical part of Braintrust’s platform. They power evaluation and observability pipelines across a wide range of environments, frameworks, and AI providers.\n\nThis role is ideal for engineers who are passionate about developer experience, API craftsmanship, and building fast, reliable, and idiomatic libraries. You’ll own the f",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "LLM Engineering"
    ],
    "matchScore": 84,
    "matchReason": "Early AI team (Series A (AI Eval)). Matches your stack in Autonomous Tool Calling.",
    "isInternship": false,
    "companyStage": "Series A (AI Eval)",
    "isIndia": false,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "ashby-cognition-1e47fa81-bfe3-436c-a6f7-fccd66a98b1e",
    "company": "Cognition",
    "title": "Partner Deployed Engineer - APAC",
    "location": "India",
    "url": "https://jobs.ashbyhq.com/cognition/1e47fa81-bfe3-436c-a6f7-fccd66a98b1e",
    "description": "WE ARE AN APPLIED AI LAB BUILDING END-TO-END SOFTWARE AGENTS.\n\nWe're the makers of Devin, the first AI software engineer. \n\nOur team is extremely talent-dense. Among our founding team, we have world-class competitive programmers, former founders, and leaders from companies at the cutting edge of AI including Scale AI, Palantir, Cursor, Waymo, Tesla, Lunchclub, Modal, Google DeepMind, and Nuro.\n\nBuilding Devin is just the first step—our hardest challenges still lie ahead. If you’re excited to solve some of the world’s biggest problems and build AI that can reason on real-world tasks, apply to join us.\n\n\nABOUT THE ROLE\n\nAt Cognition, partners are force multipliers. Partner Deployed Engineers (Partner DEs) are partner-facing (and customer-facing) technical experts who enable services partners such as Global Systems Integrators to successfully deploy, scale, and deliver value with Devin and Windsurf across their client base.\n\nIn this role, you will work closely with partner solution archit",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 84,
    "matchReason": "🇮🇳 India Role — Early AI team (Series A (Devin Autonomous AI)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Series A (Devin Autonomous AI)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "google-solvusai-1790189773-2",
    "company": "SolvusAI",
    "title": "AI Engineer Intern",
    "location": "Remote (Worldwide)",
    "url": "https://in.linkedin.com/jobs/view/ai-engineer-intern-at-solvusai-4327962417",
    "description": "This is a full-time, paid AI Engineer Intern position for candidates with 0-1 year experience. The role is remote and offers an immediate start date.",
    "postedDate": "Recently",
    "source": "Google (via LinkedIn)",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 83,
    "matchReason": "🎓 Fresher / Intern Friendly — GenAI team (Discovered via Google Jobs). Matches your stack in Python & AI Engineering.",
    "isInternship": true,
    "companyStage": "Discovered via Google Jobs",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "ashby-atlan-b2b880ed-63cd-4f56-8313-87f143fa9807",
    "company": "Atlan",
    "title": "Field Security Engineer",
    "location": "India",
    "url": "https://jobs.ashbyhq.com/atlan/b2b880ed-63cd-4f56-8313-87f143fa9807",
    "description": "WHO WE ARE\n\nAtlan is building the context layer for enterprise AI. Enterprises are pouring money into AI and most of it dies in production because the AI does not understand the business context around the data. That is the problem Atlan solves.\n\nGartner has named context the defining issue in enterprise AI, and calls context graphs the essential infrastructure for AI agents, naming Atlan one of three vendors already building it. We are also the only vendor named a Leader across all four major Gartner and Forrester evaluations for data catalogs, data governance and metadata management, the foundation the context layer runs on.\n\nCome build the infrastructure that AI runs on.\n\nSecurity is a reason Atlan's customers say yes. This role is why. You'll be the technical security voice customers hear on calls and read in their reviews, the engineer who builds the systems that make those reviews faster and increasingly self-serve, and a contributor to the compliance program that keeps Atlan tru",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 83,
    "matchReason": "🇮🇳 India Role — GenAI team (Series B (India AI/Data)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Series B (India AI/Data)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "gh-anthropic-5424310008",
    "company": "Anthropic",
    "title": "Applied AI Architect",
    "location": "Bangalore, India",
    "url": "https://job-boards.greenhouse.io/anthropic/jobs/5390746008",
    "description": "&lt;div class=&quot;content-intro&quot;&gt;&lt;h2&gt;&lt;strong&gt;About Anthropic&lt;/strong&gt;&lt;/h2&gt;\n&lt;p&gt;Anthropic’s mission is to create reliable, interpretable, and steerable AI systems. We want AI to be safe and beneficial for our users and for society as a whole. Our team is a quickly growing group of committed researchers, engineers, policy experts, and business leaders working together to build beneficial AI systems.&lt;/p&gt;&lt;/div&gt;&lt;h2 class=&quot;heading&quot;&gt;&lt;strong&gt;About the role&lt;/strong&gt;&lt;/h2&gt;\n&lt;p&gt;As an Applied AI team member at Anthropic India, you will be a Pre-Sales architect focused on becoming a trusted technical advisor helping large enterprises across India and the Asia-Pacific region understand the value of Claude and paint the vision on how they can successfully integrate and deploy Claude into their technology stack. You&#39;ll combine your deep technical expertise with customer-facing skills to architect innovative LL",
    "postedDate": "Recently",
    "source": "Greenhouse",
    "techStack": [
      "GenAI",
      "Python",
      "LLMs"
    ],
    "matchScore": 83,
    "matchReason": "🇮🇳 India Role — GenAI team (Frontier AI Lab). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Frontier AI Lab",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "gh-razorpaysoftwareprivatelimited-4699107005",
    "company": "Razorpaysoftwareprivatelimited",
    "title": "Product Manager II - AI ",
    "location": "Bengaluru",
    "url": "https://job-boards.greenhouse.io/razorpaysoftwareprivatelimited/jobs/4699107005",
    "description": "&lt;div class=&quot;content-intro&quot;&gt;&lt;p&gt;Razorpay is one of India’s leading full-stack financial technology companies, powering the way businesses move, manage, and grow money. Founded in 2014 by Harshil Mathur and Shashank Kumar with a simple vision - to simplify payments for Indian businesses - we’ve since grown into a fintech powerhouse driving India’s digital payment revolution.&lt;/p&gt;\n&lt;p&gt;Razorpay powers millions of businesses with a smarter, scalable stack that goes beyond transactions to help them truly build and grow.&lt;/p&gt;\n&lt;p&gt;From building AI-native agentic payments, to AI-assisted fraud detection and real-time risk intelligence to automated reconciliation, smart payouts, and predictive financial insights, we are embedding intelligence across our stack to make money movement faster, safer, and more efficient. In close collaboration with ecosystem partners - including banks, networks, regulators - we are pioneering industry-first solutions that are ",
    "postedDate": "Recently",
    "source": "Greenhouse",
    "techStack": [
      "Multi-Agent Workflows"
    ],
    "matchScore": 83,
    "matchReason": "🇮🇳 India Role — GenAI team (Growth (FinTech & AI)). Matches your stack in Python & AI Engineering.",
    "isInternship": false,
    "companyStage": "Growth (FinTech & AI)",
    "isIndia": true,
    "isFresher": false,
    "isApplied": false
  }
];
