import type { JobPostingItem } from "./types";

export const defaultJobs: JobPostingItem[] = [
  {
    "id": "curated-langchain-intern",
    "company": "LangChain",
    "title": "Generative AI & LLM Systems Engineering Intern",
    "location": "Remote (Worldwide)",
    "url": "https://boards.greenhouse.io/langchain/jobs/4320145007",
    "description": "Build state-of-the-art agentic workflows, LangGraph multi-agent execution engines, and evaluations for production LLM applications. Working directly with LangChain and LangGraph core engineers.",
    "postedDate": "Recently",
    "source": "Greenhouse",
    "techStack": [
      "LangChain",
      "LangGraph",
      "Multi-Agent Workflows",
      "Autonomous Tool Calling",
      "FastAPI (REST & SSE)",
      "Python"
    ],
    "matchScore": 98,
    "matchReason": "🌐 100% Remote | 🎓 Fresher / Intern Friendly — Direct fit: LangGraph, LangChain, Multi-Agent Workflows, and Autonomous Tool Calling.",
    "isInternship": true,
    "companyStage": "Series A (Agent Framework)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-composio-applied-ai",
    "company": "Composio",
    "title": "Applied AI Engineer - Autonomous Tool Calling & Agents",
    "location": "Remote (Worldwide)",
    "url": "https://jobs.ashbyhq.com/composio/a2fd44d1-1457-4248-8d9c-905953016398",
    "description": "Build autonomous tool-calling integrations, multi-agent execution pipelines, and agent reliability guardrails for 200+ developer tools. Working with LangChain, LangGraph, and Python in a distributed remote team.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Autonomous Tool Calling",
      "Multi-Agent Workflows",
      "LangGraph",
      "LangChain",
      "FastAPI (REST & SSE)",
      "Python"
    ],
    "matchScore": 98,
    "matchReason": "🌐 100% Remote | 🎓 Fresher / Intern Friendly — Direct founder review. Core alignment with your Tool Calling, LangGraph & Multi-Agent stack.",
    "isInternship": false,
    "companyStage": "Seed (Agent Tooling & Workflows)",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-mem0-ai-eng",
    "company": "Mem0",
    "title": "Full Stack AI Engineer (Agent Memory & Vector Search)",
    "location": "Remote (Worldwide)",
    "url": "https://jobs.ashbyhq.com/mem0/642f00ec-c220-48a5-9a4d-4af67875032c",
    "description": "Develop long-term memory for AI agents, multi-agent context engineering, and pgvector/Supabase retrieval systems. Working with Python, Next.js, and FastAPI.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Multi-Agent Workflows",
      "Vector DB",
      "pgvector & Supabase",
      "FastAPI (REST & SSE)",
      "Next.js & React",
      "Python"
    ],
    "matchScore": 97,
    "matchReason": "🌐 100% Remote — Direct founder review (Seed). Matches your stack in Context Engineering, pgvector, Vector DB & FastAPI.",
    "isInternship": false,
    "companyStage": "Seed (Agent Memory)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-llamaindex-rag-eng",
    "company": "LlamaIndex",
    "title": "Developer Engineer - RAG & Agent Frameworks",
    "location": "Remote (Global)",
    "url": "https://jobs.ashbyhq.com/llamaindex",
    "description": "Build advanced Corrective RAG (CRAG) pipelines, evaluation harnesses (DeepEval/Ragas), and multi-agent retrieval tools for developers. Python, TypeScript, and Vector DBs.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Corrective RAG (CRAG)",
      "RAG & Vector Search",
      "Ragas & DeepEval",
      "Vector DB",
      "Python",
      "TypeScript"
    ],
    "matchScore": 96,
    "matchReason": "🌐 100% Remote — Series A team (LLM Data). Core alignment with your Corrective RAG (CRAG) & Vector DB stack.",
    "isInternship": false,
    "companyStage": "Series A (LLM Data)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-vapi-agent-eng",
    "company": "Vapi",
    "title": "Member of Technical Staff - Agentic Developer Experience",
    "location": "Remote (Worldwide)",
    "url": "https://jobs.ashbyhq.com/vapi/0d4f1420-2590-4a38-aac4-3efda12eadb0",
    "description": "Develop real-time autonomous voice agents, function-calling harnesses, and streaming low-latency LLM orchestration pipelines using Python and FastAPI.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Multi-Agent Workflows",
      "Autonomous Tool Calling",
      "FastAPI (REST & SSE)",
      "Python",
      "TypeScript"
    ],
    "matchScore": 96,
    "matchReason": "🌐 100% Remote — Frontier voice agent platform. Strong fit for your Autonomous Tool Calling & FastAPI streaming stack.",
    "isInternship": false,
    "companyStage": "Seed (Voice AI & Agents)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-perplexity-model-eng",
    "company": "Perplexity AI",
    "title": "Member of Technical Staff (Model Behavior & Retrieval)",
    "location": "Remote (Worldwide)",
    "url": "https://jobs.ashbyhq.com/perplexity/2c6ae16b-d03e-4e33-9d32-362c5388e956",
    "description": "Build cutting-edge conversational search retrieval pipelines, prompt evaluations, and model behavior guardrails using Python, PyTorch, and Vector Search.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "RAG & Vector Search",
      "Pydantic Guardrails",
      "PyTorch",
      "Python",
      "Vector DB"
    ],
    "matchScore": 95,
    "matchReason": "🌐 100% Remote — High callback frontier AI search team. Matches your RAG, Vector Search & Guardrails capabilities.",
    "isInternship": false,
    "companyStage": "Series B (Conversational Search)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-cognition-applied-eng",
    "company": "Cognition",
    "title": "Applied AI & Systems Engineer (Devin Autonomous Platform)",
    "location": "Remote (Global)",
    "url": "https://jobs.ashbyhq.com/cognition/1e47fa81-bfe3-436c-a6f7-fccd66a98b1e",
    "description": "Develop autonomous software engineering agents, tool integration sandbox environments, and LLM reasoning loops with Python, TypeScript, and Docker.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Multi-Agent Workflows",
      "Autonomous Tool Calling",
      "Docker",
      "Python",
      "TypeScript"
    ],
    "matchScore": 95,
    "matchReason": "🌐 100% Remote — Creators of Devin AI. Ideal fit for your Agent Workflows, Tool Calling & Docker deployment skills.",
    "isInternship": false,
    "companyStage": "Series A (Devin Autonomous AI)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-modal-ai-eng",
    "company": "Modal Labs",
    "title": "Applied AI Engineer (Serverless LLM Inference & Multi-Agent Infra)",
    "location": "Remote (Worldwide)",
    "url": "https://jobs.ashbyhq.com/modal",
    "description": "Build high-throughput serverless GPU orchestration, multi-agent sandbox execution environments, and vLLM acceleration pipelines with Python and FastAPI.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Python",
      "FastAPI (REST & SSE)",
      "AWS & Docker (CI/CD)",
      "PyTorch",
      "Multi-Agent Workflows"
    ],
    "matchScore": 95,
    "matchReason": "🌐 100% Remote — Series A compute infra leader. Exceptional match for Python, FastAPI, Docker, and agent deployment.",
    "isInternship": false,
    "companyStage": "Series A (AI Compute)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-braintrust-eval-eng",
    "company": "Braintrust",
    "title": "AI Evals & Tracing Engineer",
    "location": "Remote (Worldwide)",
    "url": "https://jobs.ashbyhq.com/braintrust",
    "description": "Architect comprehensive LLM evaluation frameworks, prompt caching mechanisms, and observability tracing tools using Python, TypeScript, and Vector DBs.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "LangSmith (Tracing & Evals)",
      "Ragas & DeepEval",
      "Pydantic Guardrails",
      "Python",
      "TypeScript"
    ],
    "matchScore": 94,
    "matchReason": "🌐 100% Remote — Early AI team (Series A). Exact match for your Tracing, Evaluation & Guardrail expertise.",
    "isInternship": false,
    "companyStage": "Series A (AI Eval)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-sarvam-agent-remote",
    "company": "Sarvam AI",
    "title": "GenAI Applications Engineer (Agents & RAG)",
    "location": "Remote - India",
    "url": "https://jobs.ashbyhq.com/sarvam",
    "description": "Build Indic frontier GenAI agents, contextual retrieval systems (RAG), and evaluation pipelines using Python, FastAPI, and PyTorch in a remote setup.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Multi-Agent Workflows",
      "RAG & Vector Search",
      "FastAPI (REST & SSE)",
      "PyTorch",
      "Python"
    ],
    "matchScore": 95,
    "matchReason": "🌐 100% Remote | 🇮🇳 India Remote — Sovereign AI lab. Strong fit for your Agent, RAG & FastAPI background.",
    "isInternship": true,
    "companyStage": "Seed (India GenAI Lab)",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-epifi-product-builder-remote",
    "company": "Epifi",
    "title": "Product Builder Intern - GenAI & Agent Workflows",
    "location": "Remote - India",
    "url": "https://in.indeed.com/viewjob?jk=epifi-genai-intern",
    "description": "Prototype next-generation GenAI consumer experiences, agentic financial tools, and LangChain/FastAPI automated intelligence pipelines.",
    "postedDate": "Recently",
    "source": "Google (via Indeed)",
    "techStack": [
      "LangChain",
      "FastAPI (REST & SSE)",
      "Python",
      "LLM Engineering",
      "Next.js & React"
    ],
    "matchScore": 94,
    "matchReason": "🌐 100% Remote | 🇮🇳 India Remote — High response rate. Matches your LangChain, FastAPI & Fullstack AI engineering.",
    "isInternship": true,
    "companyStage": "Series C (Fintech & AI)",
    "isIndia": true,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-e2b-sandbox-eng",
    "company": "E2B",
    "title": "AI Agent Sandbox & Tool-Calling Systems Engineer",
    "location": "Remote (Worldwide)",
    "url": "https://jobs.ashbyhq.com/e2b",
    "description": "Create secure, sub-second execution sandboxes for AI agents, autonomous tool calling, and code execution pipelines. Working with Python, Docker, and TypeScript.",
    "postedDate": "Recently",
    "source": "Ashby",
    "techStack": [
      "Autonomous Tool Calling",
      "Multi-Agent Workflows",
      "AWS & Docker (CI/CD)",
      "Python",
      "TypeScript"
    ],
    "matchScore": 95,
    "matchReason": "🌐 100% Remote — YC Seed AI sandbox company. Perfect alignment with your Tool Calling & Agent workflows.",
    "isInternship": false,
    "companyStage": "Seed (AI Sandbox)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-huggingface-eval-eng",
    "company": "Hugging Face",
    "title": "Machine Learning & Open Source AI Applications Engineer",
    "location": "Remote (Worldwide)",
    "url": "https://jobs.lever.co/huggingface",
    "description": "Contribute to open-source Transformers, evaluation harnesses, and agent frameworks. Work with PyTorch, Hugging Face Hub, and FastAPI.",
    "postedDate": "Recently",
    "source": "Lever",
    "techStack": [
      "Hugging Face & PyTorch",
      "Ragas & DeepEval",
      "FastAPI (REST & SSE)",
      "Python"
    ],
    "matchScore": 94,
    "matchReason": "🌐 100% Remote — High Growth AI. Aligns with your Hugging Face, PyTorch, and open-source GenAI tooling.",
    "isInternship": false,
    "companyStage": "High Growth AI",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-cohere-rag-eng",
    "company": "Cohere",
    "title": "Member Technical Staff - Retrieval & Agentic Systems",
    "location": "Remote (Global)",
    "url": "https://jobs.lever.co/cohere",
    "description": "Build enterprise semantic search, multi-hop RAG systems, and reranking pipelines using Python, vector databases, and evaluation frameworks.",
    "postedDate": "Recently",
    "source": "Lever",
    "techStack": [
      "RAG & Vector Search",
      "Vector DB",
      "Corrective RAG (CRAG)",
      "Python",
      "TypeScript"
    ],
    "matchScore": 93,
    "matchReason": "🌐 100% Remote — Frontier LLM enterprise platform. Direct match for your RAG, CRAG, and Vector search stack.",
    "isInternship": false,
    "companyStage": "Series D (Enterprise LLMs)",
    "isIndia": false,
    "isFresher": false,
    "isApplied": false
  },
  {
    "id": "curated-together-inference-eng",
    "company": "Together AI",
    "title": "Applied AI Engineer - Cloud Inference & Fine-Tuning",
    "location": "Remote (Worldwide)",
    "url": "https://boards.greenhouse.io/together",
    "description": "Deploy ultra-fast open-source LLM endpoints, custom model fine-tuning jobs, and agent tooling using Python, vLLM, and PyTorch.",
    "postedDate": "Recently",
    "source": "Greenhouse",
    "techStack": [
      "Hugging Face & PyTorch",
      "Groq LPUs",
      "Python",
      "FastAPI (REST & SSE)",
      "AWS & Docker (CI/CD)"
    ],
    "matchScore": 93,
    "matchReason": "🌐 100% Remote — Frontier AI compute cloud. Direct fit for your model serving, PyTorch, and FastAPI experience.",
    "isInternship": false,
    "companyStage": "Series A (AI Cloud)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-pinecone-vector-eng",
    "company": "Pinecone",
    "title": "Applications Engineer - Vector Search & RAG Architectures",
    "location": "Remote (Global)",
    "url": "https://boards.greenhouse.io/pinecone",
    "description": "Design real-world RAG architectures, multi-tenant vector indexes, and contextual retrieval solutions for developer ecosystems.",
    "postedDate": "Recently",
    "source": "Greenhouse",
    "techStack": [
      "Vector DB",
      "RAG & Vector Search",
      "pgvector & Supabase",
      "Python",
      "TypeScript"
    ],
    "matchScore": 92,
    "matchReason": "🌐 100% Remote — Category-defining vector database. Tailored for your Vector DB, RAG & pgvector knowledge.",
    "isInternship": false,
    "companyStage": "Series B (Vector DB)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-anyscale-agent-eng",
    "company": "Anyscale",
    "title": "Distributed AI & Agent Systems Engineer",
    "location": "Remote (Worldwide)",
    "url": "https://jobs.lever.co/anyscale",
    "description": "Scale multi-agent workflows, Ray clusters, and LLM inference pipelines to production scale across distributed cloud infrastructure.",
    "postedDate": "Recently",
    "source": "Lever",
    "techStack": [
      "Multi-Agent Workflows",
      "AWS & Docker (CI/CD)",
      "Python",
      "FastAPI (REST & SSE)"
    ],
    "matchScore": 92,
    "matchReason": "🌐 100% Remote — Creators of Ray. Strong fit for your distributed Python, Multi-Agent, and FastAPI capabilities.",
    "isInternship": false,
    "companyStage": "Series B (Distributed AI)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-pincites-founding-eng",
    "company": "Pincites",
    "title": "Founding Engineer - Autonomous Legal AI Agents",
    "location": "Remote (Worldwide)",
    "url": "https://news.ycombinator.com/item?id=pincites-yc-remote",
    "description": "Develop autonomous contract review agents, corrective RAG retrieval engines, and multi-agent verification loops using LangGraph, Python, and Next.js.",
    "postedDate": "Recently",
    "source": "Y Combinator",
    "techStack": [
      "LangGraph",
      "Multi-Agent Workflows",
      "Corrective RAG (CRAG)",
      "pgvector & Supabase",
      "Next.js & React",
      "Python"
    ],
    "matchScore": 96,
    "matchReason": "🌐 100% Remote | 🎓 Fresher Friendly — YC S23 startup. Direct founder hiring matching your LangGraph, CRAG & Next.js stack.",
    "isInternship": false,
    "companyStage": "Seed (YC S23)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-kapa-solutions-eng",
    "company": "Kapa.ai",
    "title": "AI Solutions Engineer - Technical RAG & Agents",
    "location": "Remote (Global)",
    "url": "https://news.ycombinator.com/item?id=kapa-yc-remote",
    "description": "Deploy technical developer support agents, multi-source RAG pipelines, and automated LLM evaluations using Python, FastAPI, and vector databases.",
    "postedDate": "Recently",
    "source": "Y Combinator",
    "techStack": [
      "RAG & Vector Search",
      "Vector DB",
      "FastAPI (REST & SSE)",
      "Python",
      "TypeScript"
    ],
    "matchScore": 94,
    "matchReason": "🌐 100% Remote — YC S23 developer platform. Strong alignment with your RAG, Vector Search, and FastAPI stack.",
    "isInternship": false,
    "companyStage": "Seed (YC S23)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  },
  {
    "id": "curated-fathom-fullstack-ai",
    "company": "Fathom AI",
    "title": "Full-Stack AI Applications Engineer",
    "location": "Remote (Worldwide)",
    "url": "https://news.ycombinator.com/item?id=fathom-yc-remote",
    "description": "Build real-time meeting intelligence tools, LLM summarization agents, and streaming user interfaces using Next.js, Python, and PostgreSQL checkpointing.",
    "postedDate": "Recently",
    "source": "Y Combinator",
    "techStack": [
      "Next.js & React",
      "FastAPI (REST & SSE)",
      "Postgres Checkpointing",
      "Python",
      "TypeScript"
    ],
    "matchScore": 93,
    "matchReason": "🌐 100% Remote — YC W21 high-growth startup. Matches your Next.js, FastAPI & Postgres checkpointing stack.",
    "isInternship": false,
    "companyStage": "Series A (YC W21)",
    "isIndia": false,
    "isFresher": true,
    "isApplied": false
  }
];
